
@baseUrl = https://8080-joseaugusto-simplesprin-i9ku3ujpmoo.ws-us115.gitpod.io

###

GET {{baseUrl}}/tarefas

###

POST {{baseUrl}}/tarefas
Content-Type: application/json

{
    "descricao": "Atividade 2",
    "concluido": true
}

###

GET {{baseUrl}}/tarefas/2


###

PUT {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "descricao": "Nova atividae atualizada",
    "concluido": false
}


###
DELETE {{baseUrl}}/tarefas/2
